# Config file for https://travis-ci.org/
# Validate this file here - http://lint.travis-ci.org/

language: node_js
node_js:
  - "10"

# Speed up git clones
git:
  depth: 10
  submodules: false

# Install specific version
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install --non-interactive

script:
  - yarn test --verbose
  - yarn run build

# Monitor only these branches
branches:
  only:
  - master
  - dev

# $HOME/.cache/yarn
cache:
  yarn: true
